= Thorntail Teiid Examples

This takes you through an introduction to the concepts important to Teiid, Thorntail. Read http://teiid.github.io/teiid-documents/master/content/[Teiid Documentation] and https://docs.thorntail.io/[Thorntail Documentation]to understand different terminologies used, resources needed, and artifacts to be generated before developing a successful application. 


== Available Examples

|===
|*Quickstart Name* |*Features Demonstrated* |*Description* |*Prerequisites*

|link:rdbms-as-datasource/README.adoc[rdbms-as-datasource]
|JDBC translator, Native Query
|Shows how to transfer data from a relational database
|None

|link:vdb-datafederation/README.adoc[vdb-datafederation]
|Data Federation, JDBC translator, Data as Service, OData4, Microservice
|Shows how to expose multiple data sources for data federation and expose as a real time data service
|OpenShift, Mysql
|===

NOTE: The other examples in this repo are from previous version of Thorntail, and do not work with current version.
