= IMPORTANT: We've moved (again)

This repository shows usage of Teiid with Thorntail up to Teiid 10.2 and Thorntail versions 2.0 - 2.2.

Starting with Thorntail 2.3, the Teiid project has started to directly own the config api and fractions.  Now everything is under one convinent repo: https://github.com/teiid/teiid-thorntail

The examples can be found at https://github.com/teiid/teiid-thorntail

See https://github.com/teiid/teiid-thorntail/examples and the migration guide https://github.com/teiid/teiid-thorntail/blob/master/README.md

The new modules are compatible with Thorntail 2.2.

= Thorntail Teiid Examples

This takes you through an introduction to the concepts important to Teiid, Thorntail. Read http://teiid.github.io/teiid-documents/master/content/[Teiid Documentation] and https://docs.thorntail.io/[Thorntail Documentation] to understand different terminologies used, resources needed, and artifacts to be generated before developing a successful application. 


== Available Examples

|===
|*Quickstart Name* |*Features Demonstrated* |*Description* |*Prerequisites*

|link:rdbms-as-datasource/[rdbms-as-datasource]
|JDBC translator, Native Query
|Shows how to transfer data from a relational database
|None

|link:vdb-datafederation/[vdb-datafederation]
|Data Federation, JDBC translator, Data as Service, OData4, Microservice
|Shows how to expose multiple data sources for data federation and expose as a real time data service
|OpenShift, Mysql

|link:vdb-materialization/[vdb-materialization]
|File translator, Materialization
|Shows how to expose csv files with materialization for performance
|None

|link:salesforce-as-datasource/[salesforce-as-datasource]
|File translator, Materialization
|Shows how to expose Salesforce as a relational source.
|Salesforce

|link:webservice-as-datasource/[webservice-as-datasource]
|Webservice translator
|Shows how to expose Webservices.
|
|===
