
= What is it?

> Please raise any issues found with this example in our JIRA:
> https://issues.jboss.org/projects/TEIID

This example demonstrates:

* how to define a vdb to use loopback translator.
* how to use wildfly swarm to configure translaors, and run teiid as a swarm uber jar.

== Project `pom.xml`

The project is a normal maven project with `jar` packaging

[source,xml]
----
<packaging>jar</packaging>
----

The project adds a `<plugin>` to configure `wildfly-swarm-plugin` to create the runnable `.jar`.

[source,xml]
----
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <configuration>
    <mainClass>org.wildfly.swarm.teiid.examples.Main</mainClass>
  </configuration>
  ....
</plugin>
----

To define the needed parts of WildFly Swarm, a dependency(teiid) is added.

[source,xml]
----
<dependency>
    <groupId>org.wildfly.swarm</groupId>
    <artifactId>teiid</artifactId>
    <version>${version.wildfly-swarm}</version>
</dependency>
----

To support teiid tranalators in general, the additional dependencies are added.

[source,xml]
----
<dependency>
    <groupId>org.jboss.teiid.connectors</groupId>
    <artifactId>translator-file</artifactId>
    <version>${version.teiid}</version>
</dependency>
<dependency>
    <groupId>org.jboss.teiid.connectors</groupId>
    <artifactId>translator-jdbc</artifactId>
    <version>${version.teiid}</version>
</dependency>
----

== Project `main()`

This example configured teiid translators, datasource, resource adapter and deploy vdb programatically.

[source,java]
----
public static void main(String[] args) throws Exception {

    Swarm swarm = new Swarm();        
    swarm.fraction(new TeiidFraction().translator("h2", t -> t.module("org.jboss.teiid.translator.jdbc")));
    swarm.start();

    VDBArchive vdb = ShrinkWrap.create(VDBArchive.class);
    vdb.vdb(Main.class.getClassLoader().getResourceAsStream("loopback-vdb.xml"));
    swarm.deploy(vdb);   
}
----

> This example depend on a jboss modules, rerfer to `src/main/resources/modules` for details. Alternatively, if you want define moduls externally, you can build the modules externally, then add your modules as a dependency, teiid feature back can be used to build teiid related modules.

== Run

To build the project

[source,java]
----
mvn clean package
----

once build success, a `loopback-source-swarm.jar ` will generated under 'target' folder, run the example via

[source,java]
----
java -jar loopback-source-swarm.jar 
----

By default, jdbc transport bind on `0.0.0.0` and port `31000`, system properties can be used eto bind a specific IP and Port, to bind a IP use `-Dswarm.bind.address=127.0.0.1`, to bind a port use `-Dswarm.teiid.jdbc.port=31000`.

== Query Demonstrations

link:../simpleclient/README.adoc#_execution[Simple Java Client] for sample SQL Queries, link:../simpleclient/SQuirreL.adoc[SQuirreL Client] for a fully featured SQL Queries.

[source,sql]
----
mvn exec:java -Dvdb="Portfolio" -Dsql="SELECT * FROM SampleTable"
----
